name: Build DLL

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B build -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SevenZipWrapper
        path: build/Release/*.dll
